import{basename,buildDocumentParams,defaultOutputPath,validateExportSelection}from"./core/export-request.mjs";import{createTranslator,supportedLocale}from"./core/i18n.mjs";import{PRESETS,presetById}from"./core/presets.mjs";import{addRecent,readRecents,writeRecents}from"./core/recents.mjs";import{invoke,listen}from"./core/tauri.mjs";
const $=s=>document.querySelector(s);const state={locale:supportedLocale(localStorage.getItem("mardas.desktop.locale")||navigator.language),presetId:"general",sourcePath:"",outputPath:"",activeRequestId:null,outputResult:null,recents:readRecents()};const tr=createTranslator(state.locale);const t=k=>tr.t(k);
function locale(value){state.locale=supportedLocale(value);tr.locale=state.locale;localStorage.setItem("mardas.desktop.locale",state.locale);document.documentElement.lang=state.locale;document.documentElement.dir=state.locale==="fa"?"rtl":"ltr";$("#locale-button").textContent=state.locale==="fa"?"EN":"فا";document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));renderPresets();renderRecents();summary()}
function view(name){document.querySelectorAll(".view").forEach(e=>e.classList.remove("active"));$(`#${name}-view`).classList.add("active");$("#app-main").focus({preventScroll:true})}
function toast(message,kind="info"){const e=document.createElement("div");e.className=`toast ${kind}`;e.textContent=message;$("#toast-region").append(e);setTimeout(()=>e.remove(),4200)}
function errorText(error){const raw=typeof error==="string"?error:error?.message||String(error);if(raw==="TAURI_UNAVAILABLE")return t("noTauri");try{const data=JSON.parse(raw);return data.message||data.error?.message||raw}catch{return raw}}
function status(kind,titleKey,message,diagnostics=[]){const visual=$("#status-visual");visual.dataset.state=kind;visual.querySelector("span").textContent=kind==="error"?"!":kind==="working"?"…":"✓";$("#status-title").textContent=t(titleKey);$("#status-message").textContent=message;const box=$("#diagnostics");box.replaceChildren();for(const item of diagnostics){const row=document.createElement("div");row.className="diagnostic";row.dataset.severity=item.severity||"info";row.textContent=`${item.code?item.code+": ":""}${item.message||String(item)}${item.line?` (${item.line}${item.column?":"+item.column:""})`:""}`;box.append(row)}box.classList.toggle("hidden",!diagnostics.length)}
function working(on,mode="render"){$("#export-button").disabled=on;$("#validate-button").disabled=on;$("#choose-source").disabled=on;$("#choose-output").disabled=on;$("#cancel-button").classList.toggle("hidden",!on);$("#progress-wrap").classList.toggle("hidden",!on);if(on){$("#progress-bar").style.width="2%";$("#progress-label").textContent="2%";status("working",mode==="validate"?"validatingTitle":"renderingTitle",t(mode==="validate"?"validatingMessage":"renderingMessage"))}}
function progress(payload){const p=payload?.params??payload;if(!state.activeRequestId||String(p?.request_id)!==String(state.activeRequestId))return;const value=Math.max(0,Math.min(1,Number(p.fraction)||0)),percent=Math.round(value*100);$("#progress-bar").style.width=`${Math.max(2,percent)}%`;$("#progress-label").textContent=`${percent}%`;if(p.message)$("#status-message").textContent=p.message}
function saveRecent(path){state.recents=writeRecents(addRecent(state.recents,path));renderRecents()}
function renderRecents(){const list=$("#recent-list");list.replaceChildren();$("#recent-empty").classList.toggle("hidden",state.recents.length>0);$("#clear-recents").classList.toggle("hidden",!state.recents.length);for(const item of state.recents){const button=document.createElement("button");button.type="button";button.className="recent-item";const icon=document.createElement("span");icon.textContent="MD";const copy=document.createElement("span");copy.className="recent-copy";const title=document.createElement("strong");title.textContent=basename(item.path);const path=document.createElement("small");path.textContent=item.path;copy.append(title,path);button.append(icon,copy);button.addEventListener("click",()=>openSource(item.path,true));list.append(button)}}
function renderPresets(){const grid=$("#preset-grid");grid.replaceChildren();for(const preset of Object.values(PRESETS)){const button=document.createElement("button");button.type="button";button.className="preset";button.setAttribute("role","radio");button.setAttribute("aria-checked",String(preset.id===state.presetId));const title=document.createElement("strong");title.textContent=t(preset.titleKey);const help=document.createElement("small");help.textContent=t(preset.descriptionKey);const check=document.createElement("i");check.textContent="✓";button.append(title,help,check);button.addEventListener("click",()=>selectPreset(preset.id));grid.append(button)}}
function selectPreset(id){const p=presetById(id);state.presetId=p.id;$("#page-size").value=p.options.page_size;$("#appearance-style").value=p.options.style;$("#document-language").value=p.options.document_language;$("#include-toc").checked=Boolean(p.options.toc);renderPresets();summary()}
function summary(){const p=presetById(state.presetId),rows=[[t("preset"),t(p.titleKey)],[t("quality"),p.options.quality_profile==="strict-publication"?t("strict"):t("standard")],[t("page"),$("#page-size")?.value||p.options.page_size],[t("toc"),$("#include-toc")?.checked?t("enabled"):t("disabled")]],box=$("#preset-summary");box.replaceChildren();for(const [key,value] of rows){const row=document.createElement("div");row.className="summary-row";const label=document.createElement("span");label.textContent=key;const strong=document.createElement("strong");strong.textContent=value;row.append(label,strong);box.append(row)}}
function setPaths(source,output=""){state.sourcePath=source||"";state.outputPath=output||defaultOutputPath(state.sourcePath);$("#source-path").value=state.sourcePath;$("#output-path").value=state.outputPath;if(source)saveRecent(source)}function openSource(path,recent=false){if(!path)return;setPaths(path);view("export");if(recent)toast(t("recentOpened"))}
async function chooseSource(){try{const path=await invoke("pick_markdown_file");if(path)openSource(path)}catch(error){toast(errorText(error),"error")}}async function chooseOutput(){if(!state.sourcePath){toast(t("selectSourceFirst"),"error");return}try{const path=await invoke("pick_pdf_output",{suggested_path:state.outputPath||defaultOutputPath(state.sourcePath)});if(path){state.outputPath=path;$("#output-path").value=path}}catch(error){toast(errorText(error),"error")}}
function overrides(){return{document_language:$("#document-language").value,page_size:$("#page-size").value,style:$("#appearance-style").value,toc:$("#include-toc").checked}}
function selection(){state.sourcePath=$("#source-path").value;state.outputPath=$("#output-path").value;const errors=validateExportSelection({sourcePath:state.sourcePath,outputPath:state.outputPath});if(errors.length){status("error","errorTitle",errors.map(t).join(" "));toast(t(errors[0]),"error");return false}return true}function requestId(prefix){return`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`}
async function validateDocument(){if(!selection())return;working(true,"validate");const id=requestId("validate");state.activeRequestId=id;try{const params=buildDocumentParams({sourcePath:state.sourcePath,outputPath:state.outputPath,presetId:state.presetId,overrides:overrides()}),result=await invoke("sidecar_request",{request_id:id,method:"validate.document",params}),diagnostics=Array.isArray(result?.diagnostics)?result.diagnostics:[];status(result?.ok?"success":"error",result?.ok?"validTitle":"invalidTitle",t(result?.ok?"validMessage":"invalidMessage"),diagnostics)}catch(error){status("error","errorTitle",errorText(error))}finally{state.activeRequestId=null;working(false)}}
async function exportDocument(event){event.preventDefault();if(!selection())return;working(true);$("#success-actions").classList.add("hidden");const id=requestId("render");state.activeRequestId=id;try{const params=buildDocumentParams({sourcePath:state.sourcePath,outputPath:state.outputPath,presetId:state.presetId,overrides:overrides()}),result=await invoke("sidecar_request",{request_id:id,method:"render.document",params});state.outputResult=result;$("#progress-bar").style.width="100%";$("#progress-label").textContent="100%";status("success","successTitle",`${t("successMessage")} ${result.output_path||state.outputPath}`);$("#success-actions").classList.remove("hidden");saveRecent(state.sourcePath)}catch(error){const message=errorText(error);status("error","errorTitle",message);toast(message,"error")}finally{state.activeRequestId=null;working(false)}}
async function cancel(){if(!state.activeRequestId)return;try{await invoke("sidecar_cancel",{request_id:state.activeRequestId});toast(t("operationCancelled"))}catch(error){toast(errorText(error),"error")}}async function openOutput(reveal=false){const path=state.outputResult?.output_path||state.outputPath;if(!path)return;try{await invoke(reveal?"reveal_path":"open_path",{path})}catch(error){toast(errorText(error),"error")}}
async function engine(){const element=$("#engine-state");try{const health=await invoke("sidecar_request",{request_id:requestId("health"),method:"system.health",params:{}});element.dataset.state="ready";element.querySelector("span").dataset.i18n="engineReady";element.querySelector("span").textContent=t("engineReady");$("#runtime-detail").textContent=`${health.engine_version||""} · ${health.runtime?.platform||"local"}`}catch(error){element.dataset.state="error";element.querySelector("span").dataset.i18n="engineUnavailable";element.querySelector("span").textContent=t("engineUnavailable");$("#runtime-detail").textContent="sidecar unavailable";toast(errorText(error),"error")}}
async function launchFiles(paths){if(!Array.isArray(paths))return;const markdown=paths.find(path=>["md","markdown"].includes(String(path).split(".").at(-1)?.toLowerCase()));if(markdown)openSource(markdown)}
function bind(){["#start-quick-export","#workflow-quick"].forEach(s=>$(s).addEventListener("click",()=>view("export")));["#start-open-file","#workflow-open","#choose-source"].forEach(s=>$(s).addEventListener("click",chooseSource));$("#home-button").addEventListener("click",()=>view("start"));$("#export-back").addEventListener("click",()=>view("start"));$("#choose-output").addEventListener("click",chooseOutput);$("#validate-button").addEventListener("click",validateDocument);$("#export-form").addEventListener("submit",exportDocument);$("#cancel-button").addEventListener("click",cancel);$("#open-pdf").addEventListener("click",()=>openOutput(false));$("#reveal-pdf").addEventListener("click",()=>openOutput(true));$("#locale-button").addEventListener("click",()=>locale(state.locale==="fa"?"en":"fa"));$("#clear-recents").addEventListener("click",()=>{state.recents=writeRecents([]);renderRecents()});["#page-size","#include-toc","#appearance-style"].forEach(s=>$(s).addEventListener("change",summary))}
async function boot(){bind();locale(state.locale);selectPreset("general");status("idle","readyTitle",t("readyMessage"));try{await listen("sidecar-progress",event=>progress(event.payload));await listen("desktop-open-files",event=>launchFiles(event.payload));await launchFiles(await invoke("take_launch_files"))}catch(error){toast(errorText(error),"error")}await engine()}boot();
